// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3eLO0GfuFEyGGZzq7cNjnQp-hP_fdSog',
    appId: '1:545093369632:web:c53bb3a91d4c98436d6145',
    messagingSenderId: '545093369632',
    projectId: 'coffee-shop-4993f',
    authDomain: 'coffee-shop-4993f.firebaseapp.com',
    storageBucket: 'coffee-shop-4993f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCExZIGgucOapaABhCF_sVCjMmgsZQjoOw',
    appId: '1:545093369632:android:d0c92f62df3b11dc6d6145',
    messagingSenderId: '545093369632',
    projectId: 'coffee-shop-4993f',
    storageBucket: 'coffee-shop-4993f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNhlz7275_tgcqzNH1e36xHVakBMwAbrI',
    appId: '1:545093369632:ios:b8a7e870a33cff2d6d6145',
    messagingSenderId: '545093369632',
    projectId: 'coffee-shop-4993f',
    storageBucket: 'coffee-shop-4993f.appspot.com',
    iosBundleId: 'com.example.coffeeShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNhlz7275_tgcqzNH1e36xHVakBMwAbrI',
    appId: '1:545093369632:ios:bc78e404272fb89f6d6145',
    messagingSenderId: '545093369632',
    projectId: 'coffee-shop-4993f',
    storageBucket: 'coffee-shop-4993f.appspot.com',
    iosBundleId: 'com.example.coffeeShop.RunnerTests',
  );
}
